### PR TITLE
Use clown

### PR DESCRIPTION
**Pull request by wholesomedev**

### CODE REVIEW

**Comment by forabi** [comment]
CI is failing because async functions in deploy script are not supported in Node.js 6. This is because `.babelrc` sets `preset-env` to 8.10. I think we can add an override here?

**Comment by wholesomedev** [comment]
I managed to get `deploy.js` to partially work by transpiling its dependencies. But now that even the build environment for this Lambda is running Node 6, commands like `yarn test` are failing because the Jest tests are using async/await. What do you think we should do in this case?

**Comment by wholesomedev** [comment]
Nevermind. I see that ts-jest can use Babel to transpile. I'll need to look more into this. `clown` needs Node 8 at least.

**Comment by wholesomedev** [comment]
I think I'll keep this open until Lambda@Edge is upgraded to Node 8

**Comment by forabi** [comment]
I've updated our packages for compatibility with Node.js 6.10 and now this should work!

**Review by wholesomedev — COMMENTED** [review]
Great, thanks. LGTM!

**Pull request merged**
